id: P008063
initial_creation_type: ocr
source_metadata:
  id: bdr:W20194
  title: ཕྱེ་མ་ལེབ་དཀར་པོ།
  author: ''
  volumes:
    70eea3a168954b618022e6bf5ca7002a:
      image_group_id: I1KG23334
      title: ''
      volume_number: 1
      total_pages: 134
ebook_metadata:
  title: ཕྱེ་མ་ལེབ་དཀར་པོ།
  author: ''
  sku: P008063
  cover: cover.jpg
  layers:
  - pagination
